# Generated by Django 4.0 on 2022-01-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_pic', models.ImageField(blank=True, default='studentPic.png', null=True, upload_to='')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('invoice_fname', models.CharField(max_length=200)),
                ('invoice_lname', models.CharField(max_length=200)),
                ('student_birth', models.DateField(blank=True, null=True)),
                ('lesson_day', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], default='Lundi', max_length=20)),
                ('lesson_hour', models.TimeField(blank=True)),
                ('lesson_duration', models.CharField(choices=[('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55'), ('60', '60'), ('65', '65'), ('70', '70'), ('75', '75'), ('80', '80'), ('85', '85'), ('90', '90')], default=60, max_length=15)),
                ('lesson_frequency', models.CharField(choices=[('Hebdomadaire', 'Hebdomadaire'), ('Bimensuel', 'Bimensuel'), ('A la carte', 'A la carte')], max_length=100)),
                ('instrument', models.CharField(blank=True, max_length=40)),
                ('student_level', models.CharField(blank=True, choices=[('D1', 'Débutant 1'), ('D2', 'Débutant 2'), ('D3', 'Débutant 3'), ('I1', 'Intermédiaire 1'), ('I2', 'Intermédiaire 2'), ('I3', 'Intermédiaire 3'), ('A1', 'Avancé 1'), ('A2', 'Avancé 2'), ('A3', 'Avancé 3')], max_length=100)),
                ('student_email', models.EmailField(blank=True, max_length=254)),
                ('student_phone', models.CharField(blank=True, max_length=200)),
                ('billing_rate', models.IntegerField(default=50)),
                ('billing_currency', models.CharField(choices=[('CHF', 'CHF'), ('EUR', 'EUR')], default='CHF', max_length=20)),
                ('invoice_numbering', models.BooleanField(default=False)),
                ('invoice_email', models.EmailField(max_length=254)),
                ('invoice_phone', models.CharField(blank=True, max_length=100)),
                ('invoice_address', models.CharField(max_length=200)),
                ('invoice_postal', models.CharField(max_length=200)),
                ('invoice_city', models.CharField(max_length=200)),
                ('invoice_country', models.CharField(choices=[('Suisse', 'Suisse'), ('France', 'France')], default='Suisse', max_length=200)),
                ('payment_option', models.CharField(choices=[('Versement', 'Versement'), ('Bulletin', 'Bulletin'), ('Twint', 'Twint'), ('Cash', 'Cash')], default='Versement', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
