# Generated by Django 4.0 on 2022-01-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ClientsAPI', '0002_remove_clients_student_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, default='My School', max_length=200)),
                ('business_website', models.CharField(blank=True, default='www.myschool.com', max_length=200)),
                ('teacher_fname', models.CharField(default='Pierre', max_length=200)),
                ('teacher_lname', models.CharField(default='Dupont', max_length=200)),
                ('teacher_email', models.EmailField(default='myschool@mymail.com', max_length=254)),
                ('teacher_phone', models.CharField(blank=True, max_length=200)),
                ('teacher_address', models.CharField(default='6 chemin de Nullepart', max_length=200)),
                ('teacher_postal', models.CharField(default='1200', max_length=200)),
                ('teacher_city', models.CharField(default='Genève', max_length=200)),
                ('teacher_country', models.CharField(choices=[('Suisse', 'Suisse'), ('France', 'France')], default='Suisse', max_length=200)),
                ('teacher_bankNumber', models.CharField(default='45-875468-3', max_length=200)),
                ('teacher_iban', models.CharField(default='CH65 7654 5221 0000 4587 5468 3', max_length=200)),
                ('teacher_bicSwift', models.CharField(default='POSXF', max_length=200)),
                ('teacher_taxLabel', models.CharField(default='Taxe', max_length=50)),
                ('teacher_tax', models.IntegerField(default=0)),
                ('teacher_dueDays', models.IntegerField(default=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
