# Generated by Django 4.0 on 2022-01-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsAPI', '0003_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClientsAPI.teacher'),
        ),
    ]
