# Generated by Django 4.0 on 2022-01-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsAPI', '0004_clients_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='student_pic',
            field=models.ImageField(blank=True, default='ProfilPic.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='business_logo',
            field=models.ImageField(blank=True, default='genericLogo.png', null=True, upload_to=''),
        ),
    ]
