# Generated by Django 4.0 on 2022-01-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsAPI', '0005_clients_student_pic_teacher_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='lesson_frequency',
            field=models.CharField(choices=[('Hebdomadaire', 'Hebdomadaire'), ('Bimensuel', 'Bimensuel'), ('Libre', 'A la carte')], max_length=100),
        ),
    ]
