# Generated by Django 4.0 on 2022-01-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsAPI', '0006_alter_clients_lesson_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='lesson_frequency',
            field=models.CharField(choices=[('Quotidien', 'Quotidien'), ('Hebdomadaire', 'Hebdomadaire'), ('Bimensuel', 'Bimensuel'), ('Libre', 'A la carte')], max_length=100),
        ),
    ]
