# Generated by Django 4.0 on 2022-06-08 07:41

import ClientsAPI.CustomValidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsAPI', '0007_alter_clients_lesson_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='first_name',
            field=models.CharField(max_length=50, validators=[ClientsAPI.CustomValidators.validateCharField]),
        ),
        migrations.AlterField(
            model_name='clients',
            name='instrument',
            field=models.CharField(blank=True, max_length=50, validators=[ClientsAPI.CustomValidators.validateCharField]),
        ),
        migrations.AlterField(
            model_name='clients',
            name='invoice_address',
            field=models.CharField(max_length=80, validators=[ClientsAPI.CustomValidators.validateAddress]),
        ),
        migrations.AlterField(
            model_name='clients',
            name='invoice_city',
            field=models.CharField(max_length=80, validators=[ClientsAPI.CustomValidators.validateCharField]),
        ),
        migrations.AlterField(
            model_name='clients',
            name='invoice_country',
            field=models.CharField(choices=[('Suisse', 'Suisse'), ('France', 'France')], default='Suisse', max_length=80),
        ),
        migrations.AlterField(
            model_name='clients',
            name='invoice_email',
            field=models.EmailField(max_length=254, validators=[ClientsAPI.CustomValidators.validateEmailField]),
        ),
        migrations.AlterField(
            model_name='clients',
            name='invoice_fname',
            field=models.CharField(max_length=50, validators=[ClientsAPI.CustomValidators.validateCharField]),
        ),
        migrations.AlterField(
            model_name='clients',
            name='invoice_lname',
            field=models.CharField(max_length=50, validators=[ClientsAPI.CustomValidators.validateCharField]),
        ),
        migrations.AlterField(
            model_name='clients',
            name='invoice_phone',
            field=models.CharField(blank=True, max_length=50, validators=[ClientsAPI.CustomValidators.validatePhoneField]),
        ),
        migrations.AlterField(
            model_name='clients',
            name='invoice_postal',
            field=models.CharField(max_length=40, validators=[ClientsAPI.CustomValidators.validatePostal]),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(max_length=50, validators=[ClientsAPI.CustomValidators.validateCharField]),
        ),
        migrations.AlterField(
            model_name='clients',
            name='lesson_frequency',
            field=models.CharField(choices=[('Quotidien', 'Quotidien'), ('Hebdomadaire', 'Hebdomadaire'), ('Bimensuel', 'Bimensuel'), ('Libre', 'A la carte')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clients',
            name='notes',
            field=models.TextField(blank=True, validators=[ClientsAPI.CustomValidators.validateNote]),
        ),
        migrations.AlterField(
            model_name='clients',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, validators=[ClientsAPI.CustomValidators.validateEmailField]),
        ),
        migrations.AlterField(
            model_name='clients',
            name='student_level',
            field=models.CharField(blank=True, choices=[('D1', 'Débutant 1'), ('D2', 'Débutant 2'), ('D3', 'Débutant 3'), ('I1', 'Intermédiaire 1'), ('I2', 'Intermédiaire 2'), ('I3', 'Intermédiaire 3'), ('A1', 'Avancé 1'), ('A2', 'Avancé 2'), ('A3', 'Avancé 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clients',
            name='student_phone',
            field=models.CharField(blank=True, max_length=50, validators=[ClientsAPI.CustomValidators.validatePhoneField]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='business_name',
            field=models.CharField(blank=True, default='My School', max_length=50, validators=[ClientsAPI.CustomValidators.validateBusinessName]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='business_website',
            field=models.CharField(blank=True, default='www.myschool.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_address',
            field=models.CharField(default='6 chemin de Nullepart', max_length=80, validators=[ClientsAPI.CustomValidators.validateAddress]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_bankNumber',
            field=models.CharField(default='00-000000-0', max_length=100, validators=[ClientsAPI.CustomValidators.validateBankNumber]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_bicSwift',
            field=models.CharField(default='POSXF', max_length=200, validators=[ClientsAPI.CustomValidators.validateBankSwift]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_city',
            field=models.CharField(default='Genève', max_length=80, validators=[ClientsAPI.CustomValidators.validateCharField]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_country',
            field=models.CharField(choices=[('Suisse', 'Suisse'), ('France', 'France')], default='Suisse', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_email',
            field=models.EmailField(default='myschool@mymail.com', max_length=254, validators=[ClientsAPI.CustomValidators.validateEmailField]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_fname',
            field=models.CharField(default='Pierre', max_length=50, validators=[ClientsAPI.CustomValidators.validateCharField]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_iban',
            field=models.CharField(default='CH00 0000 0000 0000 0000 0000 0', max_length=100, validators=[ClientsAPI.CustomValidators.validateBankIban]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_lname',
            field=models.CharField(default='Dupont', max_length=50, validators=[ClientsAPI.CustomValidators.validateCharField]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_phone',
            field=models.CharField(blank=True, max_length=50, validators=[ClientsAPI.CustomValidators.validatePhoneField]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_postal',
            field=models.CharField(default='1200', max_length=50, validators=[ClientsAPI.CustomValidators.validatePostal]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_taxLabel',
            field=models.CharField(default='Taxe', max_length=50, validators=[ClientsAPI.CustomValidators.validateCharField]),
        ),
    ]
