# Generated by Django 4.0.6 on 2022-07-25 10:22

import ClientsAPI.CustomValidators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsAPI', '0009_teacher_teacher_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nofif_type', models.CharField(choices=[('ERROR', 'Erreur'), ('WARNING', 'Avertissement'), ('MESSAGE', 'Message'), ('INFO', 'Info')], max_length=20)),
                ('notif_message', models.CharField(max_length=50, validators=[ClientsAPI.CustomValidators.validateCharField])),
                ('notif_status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error')], max_length=20)),
                ('notif_date', models.DateField(auto_now_add=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClientsAPI.teacher')),
            ],
        ),
    ]
