# Generated by Django 4.0.6 on 2022-07-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsAPI', '0010_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='nofif_type',
            field=models.CharField(choices=[('ERROR', 'Erreur'), ('WARNING', 'Avertissement'), ('INFO', 'Info'), ('MESSAGE', 'Message')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notif_status',
            field=models.CharField(choices=[('ERROR', 'Error'), ('SUCCESS', 'Success')], max_length=20),
        ),
    ]
