# Generated by Django 4.0.6 on 2022-07-25 10:35

import ClientsAPI.CustomValidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientsAPI', '0011_alter_notifications_nofif_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='nofif_type',
        ),
        migrations.AddField(
            model_name='notifications',
            name='notif_type',
            field=models.CharField(choices=[('WARNING', 'Avertissement'), ('INFO', 'Info'), ('MESSAGE', 'Message'), ('ERROR', 'Erreur')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notif_message',
            field=models.CharField(max_length=50, null=True, validators=[ClientsAPI.CustomValidators.validateNotifMessage]),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notif_status',
            field=models.CharField(choices=[('ERROR', 'Error'), ('SUCCESS', 'Success')], max_length=20, null=True),
        ),
    ]
